#!/usr/bin/env bash

# syntax: sudo ./setup_java8

# Plaase note there are no checks here so if any directive
# fails, it will move on to the next; no exit on error

add-apt-repository ppa:webupd8team/java || exit 1
apt-get update || exit 2
apt-get install oracle-java8-installer || exit 3

#Set up environment variables

apt-get install oracle-java8-set-default || exit 4

